package src.com.seproject.emailDesigner;

import src.com.seproject.emailClientMgmtCore.EmailMessage;
import src.com.seproject.emailClientMgmtCore.RTFdoc;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoadMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class LoadMessage extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public RTFdoc LoadMessage() {
		return null;
	
	}
	
	/** */
	public void execute() {
	
	}
}
