package src.com.seproject.emailDesigner;

import src.com.seproject.emailClientMgmtCore.EmailMessage;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RedoMessageChange.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//
import src.com.seproject.emailClientMgmtCore.RTFdoc;




/** */
public class RedoMessageChange extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public EmailMessage Redo() {
		return Message;
	
	}
	
	/** */
	public void execute() {
	
	}
}
