package src.com.seproject.emailDesigner;

import src.com.seproject.emailClientMgmtCore.EmailMessage;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SaveMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class SaveMessage extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public void SaveMessage(EmailMessage message) {
	
	}
	
	/** */
	public void execute() {
	
	}
}
