package com.seproject.emailDesigner;

import com.seproject.emailClientMgmtCore.EmailMessage;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SendMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class SendMessage extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public void SendMessage(EmailMessage message) {
	
	}
	
	/** */
	public void execute() {
	
	}
}
