package com.seproject.emailDesigner;

import com.seproject.emailClientMgmtCore.EmailMessage;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UndoMessageChange.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//
import com.seproject.emailClientMgmtCore.RTFdoc;




/** */
public class UndoMessageChange extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public EmailMessage Undo() {
		return Message;
	
	}
	
	/** */
	public void execute() {
	
	}
}
