package src.com.seproject.localMessageManager;

import src.com.seproject.emailClientMgmtCore.EmailMessage;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ChairView.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class ChairView {
	/** */
	private LocalEmailManager manager;
	
	/** */
	public EmailMessage composeMessage() {
		return null;
	
	}
	
	/** */
	public void sortAddresses() {
	
	}
	
	/** */
	public void addAddresses(String list) {
	
	}
	
	/** */
	public void removeAddresses(String list) {
	
	}
	
	/** */
	public void mergeAddressList(String list) {
	
	}
	
	/** */
	public void manageSend_ReceiveAddress() {
	
	}
	
	/** */
	public int getSessionID() {
		return 0;
	
	}
	
	/** */
	public int getChairID() {
		return 0;
	
	}
}
