package src.com.seproject.localMessageManager;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailMessageParser.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailMessageParser {
	/** */
	private MessageTransceiver localMessage;
	
	/** */
	private MessageTransceiver remoteMessage;
	
	/** */
	public MessageTransceiver getEmailMessage(int userID) {
		return localMessage;
	
	}
}
