package com.seproject.localMessageManager;

import com.seproject.emailClientMgmtCore.EmailMessage;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LocalEmailManager.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class LocalEmailManager {
	/** */
	private MessageTransceiver message;
	
	/** */
	public EmailMessage getEmailMessage(int userID) {
		return null;
	
	}
	
	/** */
	public EmailMessage saveAsTemplate() {
		return null;
	
	}
	
	/** */
	public EmailMessage RetreiveTemplate(int userID, int templateID) {
		return null;
	
	}
}
