package com.seproject.localMessageManager;

import com.seproject.emailClientMgmtCore.EmailMessage;
import com.seproject.emailClientMgmtCore.Email_Client_Management_Core;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MessageTransceiver.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public interface MessageTransceiver {
	/** */
	public EmailMessage getEmailMessage(int userID);
	
	/** */
	public EmailMessage getEmailMessageRTF(int userID);
	
	/** */
	public Email_Client_Management_Core getContentManager(int userID);
}
