package com.seproject.localMessageManager;

import com.seproject.emailClientMgmtCore.EmailMessage;
import com.seproject.emailClientMgmtCore.Email_Client_Management_Core;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RemoteMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class RemoteMessage implements MessageTransceiver {
	/** */
	private EmailMessage serverMessage;
	
	/** */
	private Integer userID;
	
	/** */
	public EmailMessage SaveAsTemplate() {
		return serverMessage;
	
	}
	
	/** */
	public EmailMessage RetreiveTemplate(int userID, int templateID) {
		return serverMessage;
	
	}

	@Override
	public EmailMessage getEmailMessage(int userID) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public EmailMessage getEmailMessageRTF(int userID) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Email_Client_Management_Core getContentManager(int userID) {
		// TODO Auto-generated method stub
		return null;
	}
}
