package com.seproject.emailClientMgmtCore;

import java.util.ArrayList;
import java.util.List;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import com.seproject.JavaMail.JavaMail;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailHandler.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailHandler {
	private EmailFactory factory;
	private String recipient;
	private List<EmailMessage> sent;
	
	public EmailHandler(){
		sent = new ArrayList<EmailMessage>();
		factory = new EmailFactory();
	}
	
	
	public EmailMessage getMessage(EmailMessage newMessage) {
		if(newMessage == null){
			newMessage = factory.createEmail();
		}
		return newMessage;
	}
	
	public void sendEmail(JavaMail mail, EmailMessage email){
		try{
			mail.setMessage(new MimeMessage(mail.getSession()));
			mail.getMessage().setFrom(new InternetAddress(email.getFrom()));
			mail.getMessage().setRecipients(Message.RecipientType.TO, InternetAddress.parse(email.getTo()));
			mail.getMessage().setSubject(email.getTitle());
			mail.getMessage().setText(email.getBody());
			
			Transport.send(mail.getMessage());
			
			sent.add(email);
			email = null;
			System.out.println("Mail sent Successfully");
		}catch (MessagingException e){
			throw new RuntimeException(e);
		}
	}
	
}
