package com.seproject.emailClientMgmtCore;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailFactory.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailFactory {
	/** */
	public EmailMessage createEmail() {
		return new EmailMessage();
	}
}
