package com.seproject.emailClientMgmtCore;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Message.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public interface MessageI {
	/** */
	public void setFormat();
	
	
	/** */
	public int getSenderID();
	
	
	/** */
	public void SendMessage();
	
	
	/** */
	public void SaveMessage();
	
	/** */
	public RTFdoc LoadMessage();
	
	/** */
	public void AutoSave();
	
	/** */
	public EmailMessage Undo();
	
	/** */
	public EmailMessage Redo();
	
	/** */
	public RTFdoc getRTFCommands();
}
