package src.com.seproject.mainFacade;

import src.com.seproject.localMessageManager.ChairView;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chair.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class Chair extends User{
	/** */
	private ChairView view;
	
	/** */
	public Chair performRole() {
		return null;
	
	}
}
