package com.seproject.mainFacade;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainClass.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class MainClass {
	/** */
	static public void main(String [] args) {
		System.out.println("Test");
	}
}
