package com.seproject.mainFacade;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserSystemConfiguration.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class UserSystemConfiguration {
	/** */
	private final String defaultServerAddress = "";
	
	/** */
	private final String defaultSendAddress = "";
	
	/** */
	private final String defaultReplyAddress = "";
	
	/** */
	private String currentServerAddress;
	
	/** */
	private String currentSendAddress;
	
	/** */
	private  String currentReplyAddress;
	
	/** */
	public void configureSystem() {
	
	}
	
	/** */
	public void configureServerInfo() {
	
	}
	
	/** */
	public void configureSendAddress() {
	
	}
	
	/** */
	public void configureReplyAddress() {
	
	}
	
	/** */
	public void restoreToDefault() {
	
	}
	
	/** */
	public void configureDefaultEmailOperations() {
	
	}
}
