package src.com.seproject.mainFacade;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public abstract class User {
	private int userID;
	private long sessionID;
	private UserSystemConfiguration config;
	
	public Boolean logIn(String user, String pass){
		return null;
	}
	
	public Boolean logOut(){
		return null;
	}
	
	public Boolean changeUserName(String user){
		return null;
	}
	
	public Boolean changePassword(String pass){
		return null;
	}
	
	abstract User performRole();
}
