package com.seproject.emailClientMgmtCore;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailMessage implements Message {
	/** */
	private String message;
	
	/** */
	private String title;
	
	/** */
	private Integer emailID;
	
	/** */
	private RTFdoc messageRTF;

	@Override
	public void setFormat() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public int getSenderID() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void SendMessage() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void SaveMessage() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public RTFdoc LoadMessage() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void AutoSave() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public EmailMessage Undo() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public EmailMessage Redo() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public RTFdoc getRTFCommands() {
		// TODO Auto-generated method stub
		return null;
	}
}
