package src.com.seproject.mainFacade;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrator.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class Administrator extends User{
	/** */
	public Boolean AddUser(String user, String pass) {
		return null;
	
	}
	
	/** */
	public Boolean AddUser() {
		return null;
	
	}
	
	/** */
	public Boolean RemoveUser(User userID) {
		return null;
	
	}
	
	/** */
	public void getUserList() {
	
	}
	
	/** */
	public void setDefaultSystemSettings() {
	
	}
	
	/** */
	public void changeUserSystemConfig() {
	
	}
	
	/** */
	public Administrator performRole() {
		return null;
	
	}
}
