package com.seproject.mainFacade;

import com.seproject.emailClientMgmtCore.Email_Client_Management_Core;

import scom.seproject.summit.Summit;
import scom.seproject.summit.SummitAnnouncer;
import scom.seproject.summit.SummitObserver;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CFP_Application.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class CFP_Application implements SummitObserver {
	/** */
	private Email_Client_Management_Core emailClient;
	/** */
	private User user;
	
	/** */
	private SummitAnnouncer eventNotification;
	
	/** */
	

	CFP_Application(String username, String password){
		LinkSystems(new Administrator(), new Email_Client_Management_Core(), new SummitAnnouncer(), username, password);
		
	}
	public void LinkSystems(Administrator user, Email_Client_Management_Core emailClient, SummitAnnouncer event, String usr, String psw) {
		this.user = user;
		this.emailClient = emailClient;
		this.eventNotification = event;
		
		if(user.getConfig() == null)
			user.setConfig(new UserSystemConfiguration(emailClient.getJavaMail(), usr , psw));
	}
	
	/** */
	public Email_Client_Management_Core getClientCore() {
		return emailClient;
	}
	
	/** */
	public void runProgram() {
	}

	@Override
	public void notify(Summit summit) {
		// TODO Auto-generated method stub
	}
}
