package com.seproject.mainFacade;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.seproject.emailClientMgmtCore.Email_Client_Management_Core;
import com.seproject.emailClientMgmtCore.MergeSort;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainClass.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class MainClass {
	static CFP_Application app;
	/** */
	static public void main(String [] args) {
		System.out.println("Test");
		Email_Client_Management_Core core = new Email_Client_Management_Core();
		
		try {
			core.AddEmailAddressFromFile("res/list.txt");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	//	app = new CFP_Application();
		
	//	app.getClientCore().sendEmail();
	}
}
