package com.seproject.mainFacade;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public abstract class User {
	private int userID;
	protected long sessionID;
	protected String user;
	protected String pass;
	
	protected UserSystemConfiguration config;
	
	public boolean logIn(String user, String pass){
		this.user = user;
		this.pass = pass;
		
		return true;
	}
	
	public Boolean logOut(){
		return null;
	}
	
	public Boolean changeUserName(String user){
		return null;
	}
	
	public Boolean changePassword(String pass){
		return null;
	}
	
	public int getUserID() { return this.userID;}
	abstract User performRole();
}
