//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrator.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class Administrator extends User implements User {
	/** */
	public Boolean AddUser(String user, String pass) {
	
	}
	
	/** */
	public Boolean AddUser() {
	
	}
	
	/** */
	public Boolean RemoveUser(userID userID) {
	
	}
	
	/** */
	public void getUserList() {
	
	}
	
	/** */
	public void setDefaultSystemSettings() {
	
	}
	
	/** */
	public void changeUserSystemConfig() {
	
	}
	
	/** */
	public Administrator performRole() {
	
	}
}
