//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AutoSaveMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class AutoSaveMessage extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public void AutoSave(EmailMessage message) {
	
	}
	
	/** */
	public void execute() {
	
	}
}
