//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CFP_Application.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class CFP_Application {
	/** */
	private Email_Client_Management_Core emailClientCore();
	
	/** */
	private User() user;
	
	/** */
	private ResearchEventNotifier; eventNotification;
	
	/** */
	public void LinkSystems(User user, Email_Client_Management_Core emailClient, ResearchEventNotifier event) {
	
	}
	
	/** */
	public Email_Client_Management_Core getClientCore() {
	
	}
	
	/** */
	public void runProgram() {
	
	}
}
