//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chair.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class Chair extends User implements User {
	/** */
	private ChairView view;
	
	/** */
	public Chair performRole() {
	
	}
}
