//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ChairView.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class ChairView {
	/** */
	private LocalEmailManager manager;
	
	/** */
	public EmailMessage composeMessage() {
	
	}
	
	/** */
	public void sortAddresses() {
	
	}
	
	/** */
	public void addAddresses(String list) {
	
	}
	
	/** */
	public void removeAddresses(String list) {
	
	}
	
	/** */
	public void mergeAddressList(String list) {
	
	}
	
	/** */
	public void manageSend_ReceiveAddress() {
	
	}
	
	/** */
	public Integer getSessionID() {
	
	}
	
	/** */
	public Integer getChairID() {
	
	}
}
