//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailDesigner.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailDesigner {
	/** */
	private EmailMessage saveMessage;
	
	/** */
	private EmailMessage loadMessage;
	
	/** */
	private EmailMessage currentMessage;
	
	/** */
	private EmailMessage undo;
	
	/** */
	private EmailMessage redo;
	
	/** */
	public void SaveMessage() {
	
	}
	
	/** */
	public EmailMessage redo_() {
	
	}
	
	/** */
	public EmailMessage undo_() {
	
	}
	
	/** */
	public void AutoSave() {
	
	}
	
	/** */
	public RTFdoc LoadMessage() {
	
	}
	
	/** */
	public void SendMessage() {
	
	}
}
