//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailMessageCommand.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailMessageCommand {
	/** */
	public void execute() {
	
	}
	
	/** */
	public RTFdoc execute() {
	
	}
}
