//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Email_Client_Management_Core.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class Email_Client_Management_Core {
	/** */
	private String contacts;
	
	/** */
	private EmailMessage emailTemplate;
	
	/** */
	private EmailHandler emailHandler;
	
	/** */
	private Integer userID;
	
	/** */
	private EmailMessage currentMessage;
	
	/** */
	private EmailDesigner emailDesigner;
	
	/** */
	public Boolean sendEmail() {
	
	}
	
	/** */
	public Boolean saveAsTemplate() {
	
	}
	
	/** */
	public Boolean sortAddressListr() {
	
	}
	
	/** */
	public Boolean mergeEmailLists() {
	
	}
	
	/** */
	public Boolean AddEmailAddress(String[1..*] addressList) {
	
	}
	
	/** */
	public Boolean RemoveEmailAddress(String[1..*] addressList) {
	
	}
}
