//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class EmailMessage extends Message implements Message {
	/** */
	private String message;
	
	/** */
	private String title;
	
	/** */
	private Integer emailID;
	
	/** */
	private RTFdoc messageRTF;
}
