//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailHandler.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public abstract class EmailHandler {
	/** */
	private String recipient;
	
	/** */
	private Message newEmail;
	
	/** */
	public Boolean sendEmail() {
	
	}
}
