//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoadMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class LoadMessage extends EmailMessageCommand {
	/** */
	private EmailMessage Message;
	
	/** */
	public RTFDoc: LoadMessage() {
	
	}
	
	/** */
	public RTFdoc execute() {
	
	}
}
