//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LocalMessage.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class LocalMessage implements MessageTransceiver {
	/** */
	private EmailMessage localMessage;
	
	/** */
	private Integer userID;
	
	/** */
	public EmailMessage SaveAsTemplate() {
	
	}
	
	/** */
	public EmailMessage RetreiveTemplate(Integer userID, Integer templateID) {
	
	}
}
