//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LocalEmailManager.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class LocalEmailManager {
	/** */
	private MessageTransceiver message;
	
	/** */
	public EmailMessage getEmailMessage(Integer userID) {
	
	}
	
	/** */
	public EmailMessage saveAsTemplate() {
	
	}
	
	/** */
	public EmailMessage RetreiveTemplate(Integer userID, Integer templateID) {
	
	}
}
