//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainClass.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class MainClass {
	/** */
	public void main() {
	
	}
}
