//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Message.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public abstract class Message {
	/** */
	public Void setFormat() {
	
	}
	
	/** */
	public Integer getSenderID() {
	
	}
	
	/** */
	public void SendMessage() {
	
	}
	
	/** */
	public void SaveMessage() {
	
	}
	
	/** */
	public RTFdoc LoadMessage() {
	
	}
	
	/** */
	public void AutoSave() {
	
	}
	
	/** */
	public EmailMessage Undo() {
	
	}
	
	/** */
	public EmailMessage Redo() {
	
	}
	
	/** */
	public RTFdoc getRTFCommands() {
	
	}
}
