//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MessageTransceiver.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class MessageTransceiver {
	/** */
	public EmailMessage getEmailMessage(Integer userID) {
	
	}
	
	/** */
	public EmailMessage getEmailMessageRTF(Integer userID) {
	
	}
	
	/** */
	public Email_Client_Management_Core getContentManager(Integer userID) {
	
	}
}
