//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserSystemConfiguration.java
//  @ Date : 11/16/2014
//  @ Author : 
//
//




/** */
public class UserSystemConfiguration {
	/** */
	private final const String defaultServerAddress;
	
	/** */
	private final const String defaultSendAddress;
	
	/** */
	private final const String defaultReplyAddress;
	
	/** */
	private const String currentServerAddress;
	
	/** */
	private const String currentSendAddress;
	
	/** */
	private const  String currentReplyAddress;
	
	/** */
	public void configureSystem() {
	
	}
	
	/** */
	public void configureServerInfo() {
	
	}
	
	/** */
	public void configureSendAddress() {
	
	}
	
	/** */
	public void configureReplyAddress() {
	
	}
	
	/** */
	public void restoreToDefault() {
	
	}
	
	/** */
	public void configureDefaultEmailOperations() {
	
	}
}
